#!/bin/sh

LOCALPATH=${REQUEST_URI##${SCRIPT_NAME}/}
COMMAND=${LOCALPATH%/}

case $COMMAND in
  off)
    echo "Status: 200 OK"
    echo "Content-Type: text/plain"
    echo
    camera-control off
    ;;
  turn*)
    NO_TURNX=${COMMAND##turn?x=}
    X=${NO_TURNX%&y=*}
    Y=${NO_TURNX##*&y=}
    X=$(echo $X | grep -o '[-]\?[0-9]\+')
    Y=$(echo $Y | grep -o '[-]\?[0-9]\+')
    camera-control turn $X $Y
    ;;
  *)
    echo "Status: 400 Bad Request"
    echo "Content-Type: text/plain"
    echo
    echo "Bad request, change your URL"
esac
